Kyc Ecsp
Particeep/api-sdk-scala-with-play pull request #423
Opened 2024-02-15 13:13 UTC by LsMarsais

2024-02-15 13:45 UTC, AminJELLADParticeep approved these changes
le commit "first commit" m'a fait rire

Après il n'explique pas ce que fait l'ajout de ton code, je pense qu'il faudrait modifier ça

2024-02-20 08:41 UTC, LsMarsais commented
Cette modification du sdk a pour but de porter les features de PSFP v2 pour ngle et setup

2024-03-15 13:26 UTC, noelasne requested changes
pas de commentaires dans le sdk, l'info doit être trouvable ailleurs (doc, swagger etc.)
sauf la todo à la limite

2024-03-20 10:33 UTC, noelasne approved these changes

2024-03-20 15:13 UTC, merged