Feature/sc 59808/bug formatage de trait selle
Particeep/api-sdk-scala-with-play pull request #448
Opened 2024-04-04 13:45 UTC by LsMarsais

2024-04-04 14:27 UTC, AminJELLADParticeep commented on src/main/scala/com/particeep/api/models/kyc_ecsp/KycEcspParser.scala
> +        case _                                         => logger.error("Unexpected error, type of kyc not matching"); JsNull
en général on n'utilise pas le point virgule

2024-04-04 14:28 UTC, AminJELLADParticeep approved these changes

2024-04-04 14:36 UTC, AminJELLADParticeep commented on src/main/scala/com/particeep/api/models/kyc_ecsp/KycEcspParser.scala
> +        case _                                         => logger.error("Unexpected error, type of kyc not matching"); JsNull
j'ajoute : l'erreur n'indique pas quelle valeur on a voulu transformer en json. Du coup impossible à retracer depuis la lecture du log sur paper trail ou clevercloud

2024-04-04 14:40 UTC, AminJELLADParticeep commented on src/main/scala/com/particeep/api/models/kyc_ecsp/KycEcspParser.scala
peut-être réarranger les méthodes ici pour avoir les méthodes appelée plus bas dans le fichier

2024-04-04 14:41 UTC, AminJELLADParticeep requested changes
de la forme à revoir

2024-04-05 08:05 UTC, LsMarsais commented on src/main/scala/com/particeep/api/models/kyc_ecsp/KycEcspParser.scala
Il faut pas faire dans le sens de lecture :thinking:

2024-04-08 08:16 UTC, AminJELLADParticeep approved these changes

2024-04-09 09:27 UTC, merged