Feature/sc 65466/back pouvoir modifier le prix d une part
Particeep/api-sdk-scala-with-play pull request #501
Opened 2024-10-03 12:19 UTC by AglTour

Ajout des champs offer, amount_target et amount_target_max à RunningFundraiseEquityOption

2024-10-16 19:09 UTC, noelasne approved these changes

2024-10-16 19:13 UTC, noelasne requested changes
attention il faut faire partir la branche develop

2024-10-17 08:07 UTC, AglTour commented
> attention il faut faire partir la branche develop

C'est tout bon 👍

2024-10-22 15:19 UTC, noelasne approved these changes

2024-10-23 11:39 UTC, merged